### PR TITLE
Bug/#213/fix prices

### LINKED ISSUE #213: Bug: Prices are wrong
# Description

Price labels are wrong on deploy form

# To Reproduce:
1. Go to deploy page
1. Pick two tokens

# Expected Behaviour
Price labels should be given in Token B

# Actual Behaviour
Prices are given in Token A

# Screenshots/Videos
image (4)

# Background
Prices are hard.

### PR DESCRIPTION
**Pull request by alfetopito**
# Description

Fixes #213 

Prices labels are correctly set to `Token B`
screenshot_2020-12-04_11-19-41

Also, on Strategies, the pairs were set to `Token B` - `Token A`. I inverted it to be inline with deploy form.

# To Test
1. On deploy form
1. Pick two tokens
1. Fill in prices

- [x] Check prices are label in the selected `Token B`
- [x] Check the values at the bottom at the brackets visualization is labeled in `Token B`

1. On Strategies > Active tab
1. Expand one strategy

- [x] Check the values at the bottom at the brackets visualization is labeled in `Token B`

1. On every strategy tab (active, pending, closed)

- [x] Check the token pair is set to `Token A` - `Token B`

# Background

:crossed_fingers:

### CODE REVIEW

File: src/components/basic/display/BracketsView/Footer.tsx [hunk 1]
```diff
@@ -51,7 +51,7 @@ export const Footer = memo(function Footer(): JSX.Element {
         startPrice && (
           <PriceDisplay
             price={startPrice}
-            token={baseTokenAddress}
+            token={quoteTokenAddress}
```
Comment (nlordell) [inline src/components/basic/display/BracketsView/Footer.tsx:54]: Maybe the `PriceDisplay` should name the property `quoteToken` to save future confusion?
```suggestion
            quoteToken={quoteTokenAddress}
```

File: src/components/pages/strategies/Pending/PendingTable.tsx [hunk 2]
```diff
@@ -87,7 +87,7 @@ export const PendingTable = memo(function PendingTable({
                 <TableCell>{strategy.created.toLocaleString()}</TableCell>
                 <TableCell>
                   {strategy.quoteToken && strategy.baseToken
-                    ? `${strategy.quoteToken?.symbol} - ${strategy.baseToken?.symbol}`
+                    ? `${strategy.baseToken?.symbol} - ${strategy.quoteToken?.symbol}`
```
Comment (nlordell) [inline src/components/pages/strategies/Pending/PendingTable.tsx:90]: Nice! This always confuses me that 600 WETH-OWL (or WETH/OWL) actually means 600 OWL per 1 WETH :exploding_head:

**Review by nlordell — APPROVED** [review]
Nice! Looks correct to me (at least from the screen grab).

**Comment by gnosis-info** [comment]
Travis automatic deployment:
 * **🔐 [Safe app link](https://pr214--safecmmappreact.review.gnosisdev.com)**: To be added as a custom app on [Safe Multisig Rinkeby](https://rinkeby.gnosis-safe.io/), [Mainnet](https://gnosis-safe.io/) or [xDai](https://xdai.gnosis-safe.io)
 * **📖 [Storybook](https://pr214--safecmmappreact.review.gnosisdev.com/storybook/)**: Component stories

File: src/components/basic/display/BracketsView/Footer.tsx (hunk 1 above)
Comment (alfetopito) [reply src/components/basic/display/BracketsView/Footer.tsx]: Good idea, changed

**Review by andre-meyer — APPROVED** [review]
