### PR TITLE
Bug #105: Fix withdraw request discovery

### LINKED ISSUE #105: Bug: Critical - Withdraw Requests not correctly discovered (not allowing claim)
# Description

# To Reproduce:

# Expected Behaviour
After a withdrawRequest (and 5min later) the withdrawClaim should be available.

# Actual Behaviour
withdrawRequest was not available and the console indicates that there was no request. Further inspection shows otherwise though. See this deployment:
https://etherscan.io/tx/0x22546afa17518602ab47f49e61d3d4ff70888beeaabeef54773407b1fac3c780#eventlog

# Screenshots/Videos
image

# Environment
**Desktop:** *(Please complete)*

# Background

### PR DESCRIPTION
**Pull request by andre-meyer**
# Description

This is a UI issue where the withdrawRequest would not be successfully discovered, presenting to user the option to withdrawRequest again, which will always fail (without loss of funds or gas)

Closes #105 

# To Test
- [ ] Deploy a strategy where the quote token (right side) is priced too low to be withdrawn. (e.g. very small amount of OWL)
- [ ] Start a withdraw request
- [ ] Withdraw request should only have the amount of transactions for one side
- [ ] Withdraw request should be successfully executed
- [ ] Withdraw claim button will appear with countdown

# Background
The issue was that the previous implementation expected the first bracket to have a withdrawRequest event. Now any bracket with a withdrawRequest event will allow the UI to make a withdrawClaim

### CODE REVIEW

File: src/logic/strategy.ts [hunk 1]
```diff
@@ -101,7 +102,11 @@ class Strategy {
           fromBlock: this.startBlockNumber-1,
           filter: { batchId: bracketDepositEvents[0].batchId, user: bracketAddress }
         });
-  
+ 
+        // collect all withdrawRequest events, to determine if a strategy was withdraw requested yet
+        
+        // find blocks for all withdraw requests in order to determine time until claim is available
+        // todo: implement batchexchange time modulo to determine times more precisely
```
Comment (alfetopito) [inline src/logic/strategy.ts:109]: These times are determined based on the batch id, which is a function of the current timestamp.

https://docs.gnosis.io/protocol/docs/intro-batches/#-how-can-i-get-the-batch-id-for-a-given-time

Withdraw request events have a batchId for when that withdraw is being requested at https://github.com/gnosis/dex-contracts/blob/master/contracts/EpochTokenLocker.sol#L39

A claim is available as soon as `current batchId` > `withdraw request batchId`

Although, there is an edge case, where you'll have to wait at least another batch https://github.com/gnosis/dex-react/blob/ac63a5cbd1710bab217ccee85e3f20acc2474fc7/src/components/DepositWidget/useRowActions.tsx#L171
